"use client";

import { zodResolver } from "@hookform/resolvers/zod";
import {
  Avatar,
  Badge,
  Button,
  Card,
  CardDescription,
  CardTitle,
  Input,
  Textarea
} from "@personal-crm/ui";
import { formatRelativeLabel, formatTimelineDate, getInitials } from "@personal-crm/utils";
import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import Link from "next/link";
import { useParams } from "next/navigation";
import { useForm } from "react-hook-form";
import { toast } from "sonner";
import { z } from "zod";

import { useAuth } from "@/components/auth-provider";

const interactionSchema = z.object({
  notes: z.string().optional(),
  outcome: z.string().optional(),
  title: z.string().min(1),
  type: z.enum(["CALL", "TEXT", "EMAIL", "MEETING", "NOTE", "TASK"])
});

const followupSchema = z.object({
  channel: z.enum(["EMAIL", "TEXT", "CALL", "MEETING", "NOTE"]),
  dueAt: z.string().min(1),
  prompt: z.string().min(1),
  suggestedMessage: z.string().optional()
});

export default function ContactDetailPage() {
  const params = useParams<{ contactId: string }>();
  const { api } = useAuth();
  const queryClient = useQueryClient();
  const contact = useQuery({
    queryFn: () => api.getContact(params.contactId),
    queryKey: ["contact", params.contactId]
  });
  const interactionForm = useForm<z.infer<typeof interactionSchema>>({
    defaultValues: {
      notes: "",
      outcome: "",
      title: "",
      type: "NOTE"
    },
    resolver: zodResolver(interactionSchema)
  });
  const followupForm = useForm<z.infer<typeof followupSchema>>({
    defaultValues: {
      channel: "EMAIL",
      dueAt: new Date(Date.now() + 7 * 24 * 60 * 60 * 1000).toISOString().slice(0, 10),
      prompt: "",
      suggestedMessage: ""
    },
    resolver: zodResolver(followupSchema)
  });
  const createInteraction = useMutation({
    mutationFn: (values: z.infer<typeof interactionSchema>) =>
      api.createInteraction({
        ...values,
        contactId: params.contactId
      }),
    onSuccess: async () => {
      toast.success("Interaction logged");
      interactionForm.reset();
      await queryClient.invalidateQueries({ queryKey: ["contact", params.contactId] });
    }
  });
  const createFollowup = useMutation({
    mutationFn: (values: z.infer<typeof followupSchema>) =>
      api.createFollowup({
        ...values,
        contactId: params.contactId,
        dueAt: new Date(values.dueAt).toISOString()
      }),
    onSuccess: async () => {
      toast.success("Follow-up scheduled");
      followupForm.reset();
      await queryClient.invalidateQueries({ queryKey: ["contact", params.contactId] });
    }
  });
  const rebuildMemory = useMutation({
    mutationFn: () => api.rebuildContactMemory(params.contactId),
    onSuccess: () => toast.success("Memory rebuild queued")
  });

  if (contact.isLoading) {
    return <div className="h-96 animate-pulse rounded-[2rem] bg-muted" />;
  }

  if (!contact.data) {
    return <p>Contact not found.</p>;
  }

  const person = contact.data;

  return (
    <div className="space-y-6">
      <Link className="text-sm text-muted-foreground" href="/contacts">
        &lt; Back to contacts
      </Link>
      <header className="grid gap-4 rounded-[2rem] border border-border bg-card/90 p-6 shadow-soft lg:grid-cols-[1fr_360px]">
        <div className="flex items-start gap-4">
          <Avatar className="h-20 w-20 text-xl" imageUrl={person.avatarUrl}>
            {getInitials(person.firstName, person.lastName)}
          </Avatar>
          <div className="space-y-3">
            <div>
              <h1 className="font-display text-4xl font-semibold">{person.firstName} {person.lastName}</h1>
              <p className="text-muted-foreground">
                {person.title ?? "No title"} {person.companyName ? `at ${person.companyName}` : ""}
              </p>
            </div>
            <div className="flex flex-wrap gap-2">
              {person.tags.map((tag) => (
                <Badge key={tag.id}>{tag.name}</Badge>
              ))}
            </div>
          </div>
        </div>
        <Card className="bg-background">
          <p className="text-sm text-muted-foreground">Relationship health</p>
          <p className="mt-1 text-4xl font-semibold">{person.warmthScore}</p>
          <p className="mt-2 text-sm text-muted-foreground">
            {person.staleDays} days since last touchpoint.
          </p>
        </Card>
      </header>

      <section className="grid gap-4 lg:grid-cols-[1fr_380px]">
        <div className="space-y-4">
          <Card className="space-y-4">
            <div className="flex items-center justify-between gap-4">
              <div>
                <CardTitle>Relationship brief</CardTitle>
                <CardDescription>Generated by the memory and timeline summary agents.</CardDescription>
              </div>
              <Button disabled={rebuildMemory.isPending} onClick={() => rebuildMemory.mutate()} type="button" variant="secondary">
                Rebuild
              </Button>
            </div>
            {person.summary ? (
              <div className="space-y-3">
                <p>{person.summary.brief}</p>
                <div className="flex flex-wrap gap-2">
                  {person.summary.keyFacts.map((fact) => (
                    <Badge key={fact}>{fact}</Badge>
                  ))}
                </div>
                <p className="rounded-2xl bg-accent p-4 text-sm text-accent-foreground">
                  Next best action: {person.summary.nextBestAction}
                </p>
              </div>
            ) : (
              <p className="text-sm text-muted-foreground">No summary yet. Log an interaction to trigger one.</p>
            )}
          </Card>

          <Card className="space-y-4">
            <div>
              <CardTitle>Timeline</CardTitle>
              <CardDescription>Calls, texts, emails, meetings, notes, and tasks.</CardDescription>
            </div>
            <div className="space-y-3">
              {person.interactions.map((interaction) => (
                <div className="rounded-2xl border border-border bg-background p-4" key={interaction.id}>
                  <div className="flex items-center justify-between gap-3">
                    <p className="font-semibold">{interaction.title}</p>
                    <Badge>{interaction.type}</Badge>
                  </div>
                  <p className="mt-1 text-sm text-muted-foreground">
                    {formatTimelineDate(interaction.happenedAt)} by {interaction.createdByName}
                  </p>
                  {interaction.notes ? <p className="mt-3 text-sm">{interaction.notes}</p> : null}
                </div>
              ))}
            </div>
          </Card>
        </div>

        <aside className="space-y-4">
          <Card className="space-y-4">
            <div>
              <CardTitle>Log interaction</CardTitle>
              <CardDescription>Updates the timeline and memory model.</CardDescription>
            </div>
            <form className="space-y-3" onSubmit={interactionForm.handleSubmit((values) => createInteraction.mutate(values))}>
              <select className="h-11 w-full rounded-xl border border-border bg-background px-3 text-sm" {...interactionForm.register("type")}>
                {["CALL", "TEXT", "EMAIL", "MEETING", "NOTE", "TASK"].map((type) => (
                  <option key={type}>{type}</option>
                ))}
              </select>
              <Input placeholder="Title" {...interactionForm.register("title")} />
              <Textarea placeholder="Notes" {...interactionForm.register("notes")} />
              <Input placeholder="Outcome" {...interactionForm.register("outcome")} />
              <Button className="w-full" disabled={createInteraction.isPending} type="submit">
                Log interaction
              </Button>
            </form>
          </Card>

          <Card className="space-y-4">
            <div>
              <CardTitle>Schedule follow-up</CardTitle>
              <CardDescription>Creates an in-app reminder and agent job.</CardDescription>
            </div>
            <form className="space-y-3" onSubmit={followupForm.handleSubmit((values) => createFollowup.mutate(values))}>
              <select className="h-11 w-full rounded-xl border border-border bg-background px-3 text-sm" {...followupForm.register("channel")}>
                {["EMAIL", "TEXT", "CALL", "MEETING", "NOTE"].map((type) => (
                  <option key={type}>{type}</option>
                ))}
              </select>
              <Input type="date" {...followupForm.register("dueAt")} />
              <Textarea placeholder="Prompt" {...followupForm.register("prompt")} />
              <Textarea placeholder="Suggested message" {...followupForm.register("suggestedMessage")} />
              <Button className="w-full" disabled={createFollowup.isPending} type="submit">
                Schedule follow-up
              </Button>
            </form>
          </Card>

          <Card className="space-y-3">
            <CardTitle>Open follow-ups</CardTitle>
            {person.followups.slice(0, 5).map((followup) => (
              <div className="rounded-2xl bg-muted p-3" key={followup.id}>
                <p className="font-semibold">{followup.prompt}</p>
                <p className="text-sm text-muted-foreground">{formatRelativeLabel(followup.dueAt)}</p>
              </div>
            ))}
          </Card>
        </aside>
      </section>
    </div>
  );
}
